fields:
  key:
    type: text
  fields:
    type: section
    display: Fields
  collection:
    type: collections
    display: Collection
  title:
    type: text
    width: 50
    display: Story Title
  content:
    type: text
    width: 50
    display: Story Content    
  excerpt:
    type: text
    width: 50
    display: Story Excerpt  
  featured_image:
    type: text
    width: 50
    display: Featured Image
  seo_title:
    type: text
    width: 50
    display: Story SEO title
  seo_description:
    type: text
    width: 50
    display: Story SEO description
  tags:
    type: text
    width: 50
    display: Tags    
  categories:
    type: text
    width: 50
    display: Categories    
  author_email:
    type: text
    width: 50
    display: Author email     
  author_fullname:
    type: text
    width: 50
    display: Author full name
  custom_fields:
      type: grid
      fields:
        sc_field:
            type: text
            display: Storychie Custom field code        
        st_field:
            type: text
            display: Statamic field slug
        







  