fields:
  key:
    type: text
    validate: required
  collection:
    type: collections
    validate: required|max:1
  fields_section:
    type: section
  title:
    type: text
    validate: required
  content:
    type: text
    validate: required
  excerpt:
    type: text
  featured_image:
    type: text
  seo_title:
    type: text
  seo_description:
    type: text
  tags:
    type: text
  categories:
    type: text
  author_email:
    type: text
  author_fullname:
    type: text
  language:
    type: text
  custom_fields_section:
      type: section
  custom_fields:
      type: grid
      fields:
        sc_field:
            type: text
            display: Storychief Custom field code
        st_field:
            type: text
            display: Statamic field slug








